"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import Lenis from "lenis";
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, Command, Headphones, Linkedin, Mail, Menu, Play, Search, X } from "lucide-react";
import Scene from "./Scene";
import { experience, process, profile, proof, services, strengths, tools } from "../data/portfolio";
gsap.registerPlugin(ScrollTrigger);

export default function Portfolio(){
 const root=useRef<HTMLDivElement>(null);
 const [menuOpen,setMenuOpen]=useState(false),[commandOpen,setCommandOpen]=useState(false),[videoOpen,setVideoOpen]=useState(false),[expIndex,setExpIndex]=useState(0),[activeService,setActiveService]=useState(0);
 const activeExperience=experience[expIndex];
 useEffect(()=>{const lenis=new Lenis({duration:1.15,smoothWheel:true,anchors:true});const raf=(time:number)=>lenis.raf(time);lenis.on("scroll",ScrollTrigger.update);gsap.ticker.add(raf);gsap.ticker.lagSmoothing(0);const ctx=gsap.context(()=>{gsap.from(".hero-kicker",{y:30,opacity:0,duration:1,ease:"power3.out",delay:.15});gsap.from(".hero-line",{yPercent:110,opacity:0,stagger:.08,duration:1.15,ease:"power4.out",delay:.2});gsap.from(".hero-meta,.hero-lede,.hero-actions",{y:25,opacity:0,stagger:.08,duration:.8,ease:"power3.out",delay:.65});gsap.utils.toArray<HTMLElement>(".reveal").forEach(el=>gsap.fromTo(el,{y:70,opacity:0},{y:0,opacity:1,duration:1,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 84%",once:true}}));gsap.to(".hero-scene",{yPercent:10,scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});gsap.to(".marquee-track",{xPercent:-22,ease:"none",scrollTrigger:{trigger:".marquee",start:"top bottom",end:"bottom top",scrub:true}});},root);return()=>{ctx.revert();lenis.destroy();gsap.ticker.remove(raf)};},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setCommandOpen(v=>!v)}if(e.key==="Escape"){setCommandOpen(false);setMenuOpen(false);setVideoOpen(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 const jump=(id:string)=>{setCommandOpen(false);setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
 const navItems=useMemo(()=>[["about","About"],["services","Services"],["experience","Experience"],["proof","Proof"],["contact","Contact"]],[]);
 return <div ref={root} className="site"><div className="grain"/><div className="ambient ambient-a"/><div className="ambient ambient-b"/>
 <header className="nav"><button className="brand" onClick={()=>jump("top")} aria-label="Back to top"><span>AZ</span><strong>ABDULRAHMAN<br/>ZIDAN</strong></button><nav className={menuOpen?"nav-links open":"nav-links"}>{navItems.map(([id,label])=><button key={id} onClick={()=>jump(id)}>{label}</button>)}</nav><div className="nav-actions"><button className="cmd-trigger" onClick={()=>setCommandOpen(true)}><Command size={13}/><span>⌘K</span></button><button className="hire" onClick={()=>jump("contact")}>Hire me <ArrowUpRight size={15}/></button></div><button className="menu" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button></header>
 <main id="top">
 <section className="hero"><div className="hero-scene"><Scene/></div><div className="hero-overlay"/><div className="hero-copy"><div className="hero-kicker eyebrow"><span className="status-dot"/> AVAILABLE FOR REMOTE WORK <span className="slash">/</span> U.S. REAL ESTATE</div><h1><span className="hero-line">REAL ESTATE</span><span className="hero-line outline">SALES &amp; LEAD</span><span className="hero-line">MANAGEMENT<span className="accent">.</span></span></h1><p className="hero-meta">{profile.roles.join("  •  ")}</p><p className="hero-lede">{profile.intro}</p><div className="hero-actions"><button className="button button-light" onClick={()=>jump("contact")}>Let’s work <ArrowDownRight size={17}/></button><button className="button button-line" onClick={()=>setVideoOpen(true)}><Play size={15} fill="currentColor"/> Watch introduction</button></div></div><div className="hero-corner">CAIRO / EGYPT<br/><span>WORKING WITH U.S. TEAMS</span></div><div className="scroll-cue"><span>SCROLL</span><i/></div></section>
 <section className="marquee" aria-hidden="true"><div className="marquee-track">{Array.from({length:6}).map((_,i)=><span key={i}>COLD CALLING <b>✦</b> LEAD MANAGEMENT <b>✦</b> APPOINTMENT SETTING <b>✦</b> VIRTUAL ASSISTANCE <b>✦</b></span>)}</div></section>
 <section id="about" className="section about"><div className="kicker">01 / ABOUT</div><div className="about-grid"><div className="reveal"><p className="display">Not another <em>CV.</em><br/>A sales operator built for the <em>pipeline.</em></p></div><div className="about-copy reveal"><p>I bring 3+ years of U.S. real estate experience into every conversation — from the first cold call to qualification, follow-up and appointment handoff.</p><p>My Computer Science background adds a natural comfort with systems, CRMs and technology. The result is a professional who can handle the conversation and the workflow behind it.</p><div className="about-links"><button onClick={()=>setVideoOpen(true)}><Play size={14}/> Hear / watch my introduction</button><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={14}/> LinkedIn <ArrowUpRight size={14}/></a></div></div></div></section>
 <section id="services" className="section services"><div className="kicker">02 / CAPABILITIES</div><div className="services-top"><h2 className="section-title reveal">One skillset.<br/><em>Four ways to deploy it.</em></h2><p className="section-note reveal">The role can change. The fundamentals stay the same: communication, qualification, consistency and ownership.</p></div><div className="service-grid">{services.map((s,i)=><motion.article key={s.number} className={activeService===i?"service active":"service"} onMouseEnter={()=>setActiveService(i)} whileHover={{y:-8}} transition={{type:"spring",stiffness:260,damping:22}}><div className="service-top"><span>{s.number}</span><small>{s.kicker}</small></div><h3>{s.title}</h3><p>{s.description}</p><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div><ArrowUpRight className="service-arrow"/></motion.article>)}</div></section>
 <section className="process"><div className="process-watermark">PIPELINE</div><div className="kicker">03 / THE METHOD</div><h2 className="process-title reveal">From first <em>hello</em><br/>to clean <em>handoff.</em></h2><div className="process-grid">{process.map(([n,title,text])=><div className="process-step reveal" key={n}><span>{n}</span><strong>{title}</strong><p>{text}</p></div>)}</div></section>
 <section id="experience" className="section experience"><div className="kicker">04 / EXPERIENCE</div><div className="experience-heading"><h2 className="section-title reveal">Experience<br/><em>that moves.</em></h2><p className="section-note reveal">Hands-on U.S. real estate experience with the flexibility to step into cold calling, lead management, appointment setting or remote sales support.</p></div><div className="experience-layout"><div className="experience-list">{experience.map((item,i)=><button key={item.role+item.company} className={i===expIndex?"experience-tab active":"experience-tab"} onClick={()=>setExpIndex(i)}><span>0{i+1}</span><b>{item.role}</b><small>{item.company}</small><ChevronRight/></button>)}</div><AnimatePresence mode="wait"><motion.div key={activeExperience.role+activeExperience.company} className="experience-detail" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} transition={{duration:.35}}><div className="detail-meta"><span>{activeExperience.period}</span><span>{activeExperience.company}</span></div><h3>{activeExperience.role}</h3><p className="detail-summary">{activeExperience.summary}</p><ul>{activeExperience.bullets.map(b=><li key={b}><Check size={14}/>{b}</li>)}</ul><div className="detail-tools"><span>TOOLS / SYSTEMS</span><div>{activeExperience.tools.map(t=><b key={t}>{t}</b>)}</div></div></motion.div></AnimatePresence></div></section>
 <section id="proof" className="section proof"><div className="kicker">05 / PROOF OF FIT</div><div className="proof-grid"><div><h2 className="section-title reveal">Built for teams that value <em>ownership.</em></h2><p className="section-note reveal">No inflated claims. Just a clear record of the kind of work I’m equipped to own.</p></div><div className="proof-cards">{proof.map(p=><motion.div key={p.label} className="proof-card" whileHover={{scale:1.02}}><strong>{p.value}</strong><span>{p.label}</span><p>{p.text}</p></motion.div>)}</div></div><div className="strengths"><div className="kicker">CORE STRENGTHS</div><div className="strength-list">{strengths.map((s,i)=><span key={s}><b>0{i+1}</b>{s}</span>)}</div></div></section>
 <section className="section toolkit"><div className="kicker">06 / SYSTEMS</div><div className="toolkit-grid"><div><h2 className="section-title reveal">Comfortable where <em>people meet systems.</em></h2><p className="section-note reveal">The tools can change. I learn the stack, keep the data clean and make the next action obvious.</p></div><div className="tool-cloud">{tools.map((t,i)=><motion.span key={t} whileHover={{y:-6,borderColor:"#c9a86a",color:"#f1eee7"}} transition={{type:"spring",stiffness:400}}>{String(i+1).padStart(2,"0")} / {t}</motion.span>)}</div></div></section>
 <section className="section media"><div className="kicker">07 / INTRODUCTION</div><div className="media-grid"><button className="video-card reveal" onClick={()=>setVideoOpen(true)}><div className="video-visual"><div className="video-grid"/><div className="play-orb"><Play size={23} fill="currentColor"/></div><span>PLAY / FULLSCREEN</span></div><div className="media-caption"><strong>Meet Abdulrahman</strong><small>On-site video player / introduction</small></div></button><div className="voice-card reveal"><div className="voice-top"><Headphones/><span>VOICE INTRODUCTION</span></div><h3>A short introduction,<br/><em>straight from me.</em></h3><p>Listen to the professional voice note before you decide if we should talk.</p><a href={profile.voice} target="_blank" rel="noreferrer" className="voice-button"><Play size={15} fill="currentColor"/> Listen now <ArrowUpRight size={15}/></a></div></div></section>
 <section id="contact" className="section contact"><div className="kicker">08 / CONTACT</div><div className="contact-inner"><p className="contact-eyebrow">READY WHEN YOU ARE.</p><h2>Let’s make the next<br/><em>conversation count.</em></h2><div className="contact-actions"><a href={"mailto:"+profile.email} className="contact-primary"><Mail/> {profile.email} <ArrowUpRight/></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin/> LinkedIn <ArrowUpRight/></a></div></div></section>
 </main><footer><span>© {new Date().getFullYear()} {profile.name}</span><span>REAL ESTATE / SALES / OPERATIONS</span><a href="#top">BACK TO TOP ↑</a></footer>
 <AnimatePresence>{commandOpen&&<motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={()=>setCommandOpen(false)}><motion.div className="command" initial={{y:20,scale:.98}} animate={{y:0,scale:1}} exit={{y:10,scale:.98}} onMouseDown={e=>e.stopPropagation()}><div className="command-search"><Search size={17}/><input autoFocus placeholder="Jump to a section..." onKeyDown={e=>{if(e.key==="Escape")setCommandOpen(false)}}/><kbd>ESC</kbd></div>{navItems.map(([id,label])=><button key={id} onClick={()=>jump(id)}><span>{label}</span><ArrowUpRight size={14}/></button>)}<button onClick={()=>{setCommandOpen(false);setVideoOpen(true)}}><span>Watch introduction</span><Play size={14}/></button></motion.div></motion.div>}</AnimatePresence>
 <AnimatePresence>{videoOpen&&<motion.div className="video-modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setVideoOpen(false)} aria-label="Close video"><X/></button><div className="video-shell"><video controls playsInline preload="metadata" poster="/Abdulrahman-Zidan/video-poster.svg"><source src="/Abdulrahman-Zidan/intro.mp4" type="video/mp4"/>Your browser does not support video playback.</video><div className="video-help">Add your final introduction video as public/intro.mp4 and it will play inside this player.</div></div></motion.div>}</AnimatePresence>
 </div>;
}